# global:
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   evaluation_interval: 15s
# alerting:
#   alertmanagers:
#     - static_configs:
#       - targets: []
#       scheme: http
#       timeout: 10s
#       api_version: v2
# scrape_configs:
#   - job_name: prometheus
#     honor_timestamps: true
#     scrape_interval: 15s
#     scrape_timeout: 10s
#     metrics_path: /metrics
#     scheme: http
#     static_configs:
#     - targets:
#       - localhost:9090
#   - job_name: node-exporter
#     static_configs:
#       - targets: ["node-exporter:9100"]
#   - job_name: challenge01
#     static_configs:
#     - targets: ['52.2.64.174:9100']     
#   - job_name: k8sadmin_metrics
#     static_configs:
#     - targets: ['44.195.48.129:9100']
#   - job_name: cadvisor
#     scrape_interval: 5s
#     static_configs:
#     - targets:
#       - 52.2.64.174:8080 #IP:Port of your Host running cAdvisor
#   - job_name: "cadvisor"
#     static_configs:
#       - targets: ["cadvisor:8080"]

global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets: ['alertmanager:9093']
# rule_files:
#   - "alert_rules.yml"