version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: kapil123
      POSTGRES_DB: app
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://app:kapil123@postgres:5432/app
    networks:
      - app_network
    ports:
      - "8000:8000"

networks:
  app_network:
    external: true

volumes:
  postgres_data:
