http:
  routers:
    to-nginx_test:
      rule: "Host(boss.kapilkumaria.com) && PathPrefix(/nginx)"
      middlewares:
        - nginx-strip
      service: nginx_test    
    to-backend:
      rule: "Host(boss.kapilkumaria.com) && PathPrefix(/api) || PathPrefix(/docs)"
      middlewares:
        - backend-strip
      service: backend    
    to-adminer:
      rule: "Host(boss.kapilkumaria.com) && PathPrefix(/db)"
      middlewares:
        - adminer-strip
      service: adminer       
  
  middlewares:
    nginx-strip:
      stripprefix:
        prefixes:
          - /nginx
    adminer-strip:
      stripprefix:
        prefixes:
          - /db  
    backend-strip:
      stripprefix:
        prefixes:
          - /api
          - /docs  
    
  services:
    nginx_test:
      loadBalancer:
        servers:
          - port: 80
    adminer:
      loadBalancer:
        servers:
          - port: 8080  
    backend:
      loadBalancer:
        servers:
          - port: 5000